pipeline{

    agent any 

    stages('Git checkout'){
        stage{
            script{
                   git branch: 'main', url: 'https://github.com/Gowtham7707/Docker_microservice.git'
            }
          
        }
    }
}
